### ISSUE TITLE
trying to extract a dav file failed

### ISSUE THREAD

**Issue by JacekKac** [MatrixEditor/hiktools#5]
python3 -m hiktools.fmod digicap.dav firmware
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/pi/.local/lib/python3.9/site-packages/hiktools/fmod/__main__.py", line 37, in <module>
    with DigiCap(sys.argv[1]) as dcap:
  File "/home/pi/.local/lib/python3.9/site-packages/hiktools/fmod/digicap.py", line 429, in __enter__
    self.fparse()
  File "/home/pi/.local/lib/python3.9/site-packages/hiktools/fmod/digicap.py", line 407, in fparse
    raw_data = decode_xor16(
  File "/home/pi/.local/lib/python3.9/site-packages/hiktools/fmod/digicap.py", line 263, in decode_xor16
    result.append(key_byte ^ buf[index])
IndexError: index out of range

**Comment by MatrixEditor** [comment]
Hello @JacekKac,

the problem is either

1. The firmware file is of a recent version and is therefore not supported by this library,
2. or there's a flaw in the parsing logic (which I would have to verify) 

If you are sure the latter one is causing the problem, it would be nice to share the file for investigation.

**Comment by JacekKac** [comment]
hi! sure it,s brand new firmware from KD outdoor station
https://www.hikvisioneurope.com/eu/portal/portal/Technical%20Materials/07%20%20Video%20Intercom/00%20%20Product%20Firmware/01%20Door%20Station%20%28KD%20KV%20KB%29/KD%20Series/KD8003%28B%29/V2.2.78_241012/VIS_OUTDOOR_F2pro_EN_STD_V2.2.78_241012.zip
